# Copyright 2026 Nan Zhijin
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

"""Templates and data classes for the Skill Generator."""

from dataclasses import dataclass, field
from string import Template


# ═══════════════════════════════════════════════════════════
# Data Classes
# ═══════════════════════════════════════════════════════════

@dataclass
class TaskDefinition:
    """A single task within a skill."""

    id: str
    label: str
    priority: str = "medium"
    file: str = ""

    def __post_init__(self):
        if not self.file:
            self.file = f"references/{self.id}.md"
        if self.priority not in ("high", "medium", "low"):
            raise ValueError(
                f"Task '{self.id}': priority must be high/medium/low, got '{self.priority}'"
            )


@dataclass
class SkillDefinition:
    """Complete definition of a skill to generate."""

    name: str
    description: str = ""
    version: str = "1.0"
    category: str = "general"
    tags: list = field(default_factory=list)
    author: str = ""
    output_schema: str = ""
    tasks: list = field(default_factory=list)  # list[TaskDefinition]
    perspectives: list = field(default_factory=list)  # list[str|dict]
    execution: dict = field(default_factory=dict)


# ═══════════════════════════════════════════════════════════
# Built-in Perspective Templates
# ═══════════════════════════════════════════════════════════

BUILTIN_PERSPECTIVES: dict = {
    "correctness": {
        "name": "correctness",
        "prompt": (
            "从事实准确性角度批判这条分析。引用的代码行是否存在？描述的"
            "行为是否真的发生？技术判断是否有事实错误？"
            "只指出确实有问题的地方，不要制造假问题。"
            'Respond with JSON: {"has_issues": bool, "issues": [{"point": "...", "severity": "critical|major|minor"}]}'
        ),
        "needs_context": False,
    },
    "completeness": {
        "name": "completeness",
        "prompt": (
            "从完整性的角度批判这条分析。是否遗漏了相关的安全问题？"
            "边界条件是否被考虑？有没有其他攻击向量没被提到？"
            'Respond with JSON: {"has_issues": bool, "issues": [{"point": "...", "severity": "critical|major|minor"}]}'
        ),
        "needs_context": False,
    },
    "actionability": {
        "name": "actionability",
        "prompt": (
            "从可操作性的角度批判这条分析。修复建议是否具体？"
            "一个初级工程师能否看懂并执行？是否给出了具体的代码修改方案？"
            'Respond with JSON: {"has_issues": bool, "issues": [{"point": "...", "severity": "critical|major|minor"}]}'
        ),
        "needs_context": False,
    },
    "consistency": {
        "name": "consistency",
        "prompt": (
            "从报告一致性的角度批判这条分析。这条发现和报告中的其他发现"
            "是否矛盾？严重程度评级和其他发现相比是否一致？是否有两条发现"
            "实际上说的是同一个问题？"
            'Respond with JSON: {"has_issues": bool, "issues": [{"point": "...", "severity": "critical|major|minor"}]}'
        ),
        "needs_context": True,
    },
    "severity-calibration": {
        "name": "severity-calibration",
        "prompt": (
            "从严重程度合理性的角度批判这条分析。严重等级是否合理？"
            "和同报告中其他发现的严重程度相比，是否偏高或偏低？"
            'Respond with JSON: {"has_issues": bool, "issues": [{"point": "...", "severity": "critical|major|minor"}]}'
        ),
        "needs_context": True,
    },
    "evidence-quality": {
        "name": "evidence-quality",
        "prompt": (
            "从证据质量的角度批判这条分析。发现的支撑证据是否充分？"
            "有没有'感觉像'但缺乏具体证据的断言？"
            'Respond with JSON: {"has_issues": bool, "issues": [{"point": "...", "severity": "critical|major|minor"}]}'
        ),
        "needs_context": False,
    },
    "false-positive-check": {
        "name": "false-positive-check",
        "prompt": (
            "从误报检测的角度批判这条分析。这条发现有没有可能是误报？"
            "在什么条件下它会是假阳性？"
            'Respond with JSON: {"has_issues": bool, "issues": [{"point": "...", "severity": "critical|major|minor"}]}'
        ),
        "needs_context": False,
    },
}


# ═══════════════════════════════════════════════════════════
# File Content Templates
# ═══════════════════════════════════════════════════════════

# --- SKILL.md ---
SKILL_MD_TEMPLATE = Template(
    """---
name: $name
description: $description
version: "$version"
category: $category
tags: [$tags]
author: $author

tasks:
$tasks_yaml
---
"""
)

# --- config.yaml ---
CONFIG_YAML_TEMPLATE = Template(
    """# Batch-Pool Runtime Configuration
# Generated by skill-generator

execution:
  default_model: $default_model
  max_tokens: $max_tokens
  workers: $workers
  per_task_timeout: 120.0
  max_retries: 2

api_pool:
  max_concurrent_per_key: 5

synthesis:
  strategy: merge
  sort_by: priority
  output: synthesized.json

loop:
  enabled: $loop_enabled
  max_iterations: $max_iterations        # hard cap — never exceed this
  max_parallel_items: $max_parallel_items
  stop_condition: convergence            # convergence | max_iterations
  diff_threshold: 0.2                    # 0.0-1.0 — ignore changes below 20% of content
  stability_rounds: 2                    # consecutive stable rounds → force converge
  stability_tolerance: 5                 # max score delta (±5 points) for "stable"

  # Termination logic (first to trigger wins):
  # 1. No task changed above diff_threshold → "no meaningful change"
  # 2. Score delta <= stability_tolerance for stability_rounds consecutive
  #    rounds → "converged — diminishing returns"
  # 3. max_iterations reached → "hard cap"

  perspectives:
$perspectives_yaml

  refine_prompt: >
    You have received critique from multiple perspectives on the work above.
    Integrate the feedback to improve the output.

    Principles:
    1. Only change what was flagged — preserve what works.
    2. If multiple perspectives raised the same issue, address it once.
    3. If a critique is misguided or wrong, ignore it.
    4. The output format must remain consistent with the original schema.
    5. Add a "modified_summary" field:
       - If substantive changes were made: describe what changed and why.
       - If nothing needed changing: set to empty string "".
       - For creative work: note which critiques deepened/ enriched the output.
       - For audit work: note which findings were downgraded or removed.
"""
)

# --- references/*.md skeleton ---
REFERENCE_TEMPLATE = Template(
    """# $task_label

## 背景
<!-- TODO: 描述这个分类任务的背景和目的。1-2 句话。 -->

## 分析维度
<!-- TODO: 列出具体检查项。每个维度应该是一个可操作的判断标准。 -->
1. <!-- TODO -->
2. <!-- TODO -->
3. <!-- TODO -->

## 输出格式
<!-- 保持以下 JSON schema 不变，或根据 task 特性调整字段 -->
{
  "category": "$task_id",
  "findings": [
    {
      "id": "$task_id_upper-001",
      "title": "...",
      "severity": "LOW|MEDIUM|HIGH|CRITICAL",
      "description": "...",
      "location": "文件:行号",
      "remediation": "..."
    }
  ],
  "score": 0-100,
  "summary": "..."
}

## 评估标准
<!-- TODO: 定义打分标准 -->
- 90-100: <!-- TODO -->
- 70-89: <!-- TODO -->
- 50-69: <!-- TODO -->
- <50: <!-- TODO -->
"""
)
